### ISSUE TITLE
Add production environment deployment approval

### ISSUE THREAD

**Issue by cvarjao** [BCDevOps/nr-elasticsearch-stack#40]
When deploying to prod, someone needs to approve

**Comment by DerekRoberts** [comment]
New GitHub Actions feature - Environments - has required reviewers before deploy
https://docs.github.com/en/actions/reference/environments

**Comment by DerekRoberts** [comment]
Resolved by https://github.com/BCDevOps/nr-elasticsearch-stack/pull/42
