### ISSUE TITLE
Uninstall steps in readme do not clean up all objects

### ISSUE THREAD

**Issue by 2011sandeepraj** [BCDevOps/nr-elasticsearch-stack#8]
Its been observed that following the uninstall command in the read me 
`helm uninstall nr-ess; 
oc delete pvc -l 'app in (nr-ess-master, nr-ess-data, nr-ess-ingest)';`
does not clean up secrets, and service accounts.

This ticket to ensure that all open shift objects not managed by helm are labeled in a way that 
`oc delete` instruction in the readme is expanded with the command below.

`oc delete all,configmap,pvc,serviceaccount,rolebinding 'app in (nr-ess-master, nr-ess-data, nr-ess-ingest, <newlabel>)'`

For instance, the https://github.com/BCDevOps/nr-elasticsearch-stack/blob/1.x/chart/templates/000-pre-install-00.yaml#L49, should probably follow by an oc label

Service account and rolebinding at https://github.com/BCDevOps/nr-elasticsearch-stack/blob/1.x/chart/templates/000-pre-install-01.yaml should have the same label

and Job configuration at 
https://github.com/BCDevOps/nr-elasticsearch-stack/blob/1.x/chart/templates/001-pre-install-02.yaml
should have the same label

**Comment by cvarjao** [comment]
no longer relevant for AWS/terraform deployments
